server:
  port: ${CUSTOM.SERVER.PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: license-service-query-route
          uri: lb://license-service-query
          predicates:
            - Path=/api/license/**
          filter:
            - StripPrefix=2
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.SERVER.HOSTNAME:http://localhost:9411/api/v2/spans}