server:
  port: ${CUSTOM.SERVER.PORT:8000}

spring:
  cloud:
    gateway:
      routes:
        - id: license-service-route
          uri: http://localhost:9030/
          predicates:
            - Path=/**
          