server:
  port: ${CUSTOM.SERVER.PORT:9035}

spring:
  data:
    mongodb:
      uri: mongodb://miguel:miguel@localhost:27018/miguel?authSource=admin

kafka:
  miguel:
    topic: miguel-topic-2
    port: 9092
    server: 127.0.0.1