server:
  port: ${CUSTOM.SERVER.PORT:9030}

spring:
  data:
    mongodb:
      uri: mongodb://miguel:miguel@localhost:27017/miguel?authSource=admin

# OpenAPI Configuration
springdoc:
  swagger-ui:
    enabled: true