server:
  port: ${CUSTOM.SERVER.PORT:9030}

spring:
  data:
    mongodb:
      uri: mongodb://miguel:miguel@localhost:27017/miguel?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN.SERVER.HOSTNAME:http://localhost:9411/api/v2/spans}

kafka:
  miguel:
    topic: miguel-topic
    topic2: miguel-topic-2
    port: 9092
    server: 172.18.0.1