server:
  port: ${CUSTOM.SERVER.PORT:9030}

spring:
  data:
    mongodb:
      uri: mongodb://miguel:miguel@localhost:27017/miguel?authSource=admin


# OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    csrf:
      enabled: true